apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: samplejava
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: samplejava
    spec:
      containers:
      - name: samplejava
        image: devopsdemoregistry.azurecr.io/javademo:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: samplejava
spec:
  type: LoadBalancer
  ports:
  - name: samplejava
    port: 8080
  selector:
    app: samplejava